export enum Role{
    CUSTOMER = 'CUSTOMER',
    ADMIN = 'ADMIN',
    ARTISAN = 'ARTISAN'
}

export enum Gender{
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHER = 'OTHER'
}

export enum Token {
    VERIFICATION = 'VERIFICATION',
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    PASSWORD_RESET = 'PASSWORD_RESET',
    REFRESH = 'REFRESH'
}

export enum Status {
    OPEN = 'OPEN',
    PENDING = 'PENDING',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    EXPIRED = 'EXPIRED'
}

export enum ApplicationStatus {
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
}

export enum NotificationType {
    JOB_APPLICATION_RECEIVED = 'JOB_APPLICATION_RECEIVED',
    JOB_APPLICATION_ACCEPTED = 'JOB_APPLICATION_ACCEPTED',
    JOB_STARTED              = 'JOB_STARTED',
    JOB_COMPLETION_REQUESTED = 'JOB_COMPLETION_REQUESTED',
    JOB_COMPLETED            = 'JOB_COMPLETED',
    JOB_CANCELLED            = 'JOB_CANCELLED',
    MESSAGE_RECEIVED         = 'MESSAGE_RECEIVED',
    REVIEW_RECEIVED          = 'REVIEW_RECEIVED',
}